"""
Krishva - Crop Disease Detection API
Krish (कृषि) = farming  +  Nova (नव) = new  ->  "New Farming"

A FastAPI backend that serves the MobileNetV2 crop disease classifier.

Run with:  uvicorn main:app --reload --port 8000
Then open: http://127.0.0.1:8000/docs   for interactive API docs
"""

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
import json
import io
import os
from fastapi.responses import Response

# Image size must match train_model.py IMAGE_SIZE and the MobileNetV2 input.
IMAGE_SIZE = (224, 224)

# Only these suffixes are accepted. Keeps a renamed .exe from reaching PIL.
ALLOWED_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}

# 10 MB is generous for a phone photo of a single leaf.
MAX_UPLOAD_BYTES = 10 * 1024 * 1024

# Cap on a text-to-speech request, so the endpoint cannot be abused.
MAX_SPEECH_CHARS = 1200

app = FastAPI(
    title="Krishva Crop Disease Detection API",
    description=(
        "Upload a leaf photo and get the disease, a confidence percentage "
        "and a remedy in English and Hindi."
    ),
    version="1.2.0",
)

# CORS is needed because the frontend runs on a different port than this API.
# 5500 is the old static server; 5173 is the Vite dev server; the LAN address
# is for testing a phone on the same Wi-Fi. Origins are listed explicitly
# because the CORS spec forbids a wildcard with allow_credentials=True.
# Add your deployed frontend's origin here when you host it.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5500",
        "http://127.0.0.1:5500",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://192.168.1.168:5173",
        "http://192.168.1.168:5500",
    ],
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
    allow_credentials=False,
)


# --------------------------------------------------------------------------
# Load artefacts ONCE at startup.
# Doing this at module level (not inside the request handler) means the
# 2.4M parameters are deserialised once and every request reuses a warm model.
# --------------------------------------------------------------------------
model = tf.keras.models.load_model("crop_disease_model.h5")

with open("class_names.json", "r", encoding="utf-8") as f:
    class_indices = json.load(f)

# class_names.json maps name -> index. The model predicts indices, so flip it
# to index -> name. int() is needed because JSON values arrive as strings.
index_to_class = {int(v): k for k, v in class_indices.items()}

# disease_info.json is the single source of truth for every piece of user-facing
# text in both languages, so English and Hindi can never drift apart. It also
# holds the UI strings the frontend needs to render its own labels.
with open("disease_info.json", "r", encoding="utf-8") as f:
    disease_info = json.load(f)

# The training run accidentally picked up dataset/duplicates/ as a 16th class.
# It holds no images, so this dead output unit is hidden from the API. After
# retraining on a clean dataset this set stays empty.
JUNK_CLASSES = {"duplicates"}
VALID_INDICES = [i for i in sorted(index_to_class) if index_to_class[i] not in JUNK_CLASSES]

# Interface text, so the frontend never hardcodes English or Hindi.
UI_TEXT = {
    "en": {
        "tagline": "Krish (farming) + Nova (new) = New Farming",
        "intro": "Upload a photo of a single leaf and Krishva will identify the disease, show how confident it is, and give you the remedy.",
        "analyze": "Analyze Leaf",
        "analyzing": "Analyzing the leaf, please wait...",
        "new_scan": "Diagnose another leaf",
        "generating_voice": "Generating audio...",
        "no_voice_and_no_server": (
            "Your browser has no voice for this language and the server is "
            "unreachable, so audio cannot play."
        ),
        "rank": "Rank",
        "disease": "Predicted disease",
        "remedy_for": "Remedy for",
        "replay": "Speak again",
        "results": "Results",
        "confidence": "Confidence",
        "remedy": "Remedy",
        "language": "Language",
        "voice": "Voice output",
        "voice_on": "On",
        "voice_off": "Off",
        "preview": "Predicted disease",
        "low_confidence": "Confidence is low. The photo may be blurry or badly lit. Try again with a clearer photo of a single leaf.",
        "no_remedy": "No remedy info available.",
        "voice_failed": "Could not generate audio. Check the backend and internet.",
        "server_voice_note": (
            "Your browser has no Hindi voice, so audio is generated by the "
            "server. This needs an internet connection."
        ),
        "api_down": "Could not reach the Krishva API. Make sure the backend is running: uvicorn main:app --reload",
        "not_healthy": "Remedy:",
        "footer": "Krishva - MobileNetV2 (transfer learning) on 20,764 leaf images across 15 crop disease classes, served with FastAPI.",
    },
    "hi": {
        "tagline": "कृषि (खेती) + नव (नया) = नई खेती",
        "intro": "एक पत्ती की फोटो अपलोड करें और कृष्वा बीमारी की पहचान करेगा, विश्वास स्तर बताएगा और उपाय बताएगा।",
        "analyze": "विश्लेषण करें",
        "analyzing": "पत्ती का विश्लेषण हो रहा है, कृपया प्रतीक्षा करें...",
        "new_scan": "एक और पत्ती की जाँच करें",
        "generating_voice": "आवाज़ बन रही है...",
        "no_voice_and_no_server": (
            "इस भाषा के लिए ब्राउज़र में आवाज़ नहीं है और सर्वर भी उपलब्ध नहीं है।"
        ),
        "rank": "स्थान",
        "disease": "पहचानी गई बीमारी",
        "remedy_for": "इसका उपाय",
        "replay": "फिर से सुनाएं",
        "results": "परिणाम",
        "confidence": "विश्वास स्तर",
        "remedy": "उपाय",
        "language": "भाषा",
        "voice": "आवाज़",
        "voice_on": "चालू",
        "voice_off": "बंद",
        "preview": "पहचानी गई बीमारी",
        "low_confidence": "विश्वास स्तर कम है। फोटो धुँधली या अंधेरे में हो सकती है। एक साफ़ पत्ती की फोटो के साथ फिर कोशिश करें।",
        "no_remedy": "कोई उपाय जानकारी उपलब्ध नहीं है।",
        "voice_failed": "आवाज़ नहीं बन सकी। बैकएंड और इंटरनेट जाँचें।",
        "server_voice_note": (
            "आपके ब्राउज़र में हिन्दी आवाज़ नहीं है, इसलिए आवाज़ सर्वर बनाएगा। "
            "इसके लिए इंटरनेट चाहिए।"
        ),
        "api_down": "कृष्वा API से संपर्क नहीं हो पाया। जाँचें कि बैकएंड चल रहा है: uvicorn main:app --reload",
        "not_healthy": "उपाय:",
        "footer": "कृष्वा - MobileNetV2 (ट्रांसफर लर्निंग), 20,764 पत्ती फोटो और 15 फसल रोग वर्गों पर, FastAPI से सेवा।",
    },
}


@app.get("/")
def root():
    """Health check plus the UI strings, so the frontend needs no hardcoding."""
    return {
        "name": "Krishva",
        "status": "running",
        "classes": len(VALID_INDICES),
        "docs": "/docs",
        "ui": UI_TEXT,
    }


@app.post("/api/predict")
async def predict_api(file: UploadFile = File(...)):
    """
    Classify an uploaded leaf image.

    Both languages are returned for every result, so the frontend can switch
    language instantly without uploading the image again.
    """
    filename = (file.filename or "").lower()
    if not any(filename.endswith(s) for s in ALLOWED_SUFFIXES):
        raise HTTPException(status_code=400, detail="Please upload a JPG, PNG or WEBP image.")

    contents = await file.read()

    if not contents:
        raise HTTPException(status_code=400, detail="The uploaded file is empty.")

    if len(contents) > MAX_UPLOAD_BYTES:
        raise HTTPException(status_code=413, detail="Image is larger than the 10 MB limit.")

    # BytesIO wraps the uploaded bytes in an in-memory file object so PIL can
    # read them without ever writing to disk.
    try:
        img = image.load_img(io.BytesIO(contents), target_size=IMAGE_SIZE)
    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Could not read that image. It may be corrupted or not a real image.",
        )

    # /255.0 MUST match rescale=1./255 in train_model.py, and the batch
    # dimension must be added with expand_dims. Both are silent-failure points.
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    predictions = model.predict(img_array, verbose=0)[0]

    # Rank the valid classes from highest probability to lowest.
    ranked = sorted(VALID_INDICES, key=lambda i: predictions[i], reverse=True)
    top_indices = ranked[:3]

    results = []
    for idx in top_indices:
        class_name = index_to_class[idx]
        # float() is required: predictions[idx] is a numpy.float32 and
        # json.dumps cannot serialise numpy scalars, which raised
        # "TypeError: Object of type float32 is not JSON serializable".
        confidence = round(float(100 * predictions[idx]), 2)
        info = disease_info.get(class_name, {})
        results.append(
            {
                "class": class_name,
                "confidence": confidence,
                "name_en": info.get("name_en", class_name.replace("_", " ")),
                "name_hi": info.get("name_hi", class_name.replace("_", " ")),
                "remedy_en": info.get("remedy_en", UI_TEXT["en"]["no_remedy"]),
                "remedy_hi": info.get("remedy_hi", UI_TEXT["hi"]["no_remedy"]),
            }
        )

    return JSONResponse({"results": results, "ui": UI_TEXT})


@app.post("/api/speak")
async def speak_api(payload: dict = None):
    """
    Text-to-speech, returns an audio/mpeg body.

    The browser's built-in speechSynthesis is tried first because it is free
    and offline. But Chrome on macOS frequently fails to expose non-English
    voices to it, which is why Hindi came out silent. This endpoint is the
    reliable fallback: gTTS generates real Hindi audio and the browser just
    plays the MP3 it receives.

    Requires an internet connection because gTTS calls Google.
    """
    payload = payload or {}
    text = str(payload.get("text", "")).strip()
    lang = str(payload.get("lang", "hi")).lower()

    if not text:
        raise HTTPException(status_code=400, detail="No text supplied.")
    if len(text) > MAX_SPEECH_CHARS:
        raise HTTPException(
            status_code=400,
            detail=f"Text too long, maximum {MAX_SPEECH_CHARS} characters.",
        )
    if lang not in ("hi", "en"):
        raise HTTPException(status_code=400, detail="lang must be 'hi' or 'en'.")

    try:
        from gtts import gTTS
        import tempfile

        handle, path = tempfile.mkstemp(suffix=".mp3")
        os.close(handle)
        try:
            gTTS(text=text, lang=lang).save(path)
            with open(path, "rb") as fh:
                audio = fh.read()
        finally:
            if os.path.exists(path):
                os.remove(path)
    except HTTPException:
        raise
    except Exception:
        # No internet, or Google blocked the request.
        raise HTTPException(
            status_code=503,
            detail="Server text-to-speech is unavailable. It needs an internet connection.",
        )

    # Return the MP3 inline rather than base64 in JSON. Streaming raw audio
    # avoids a ~33% size penalty and lets the browser start playing sooner.
    return Response(
        content=audio,
        media_type="audio/mpeg",
        headers={"Cache-Control": "no-store"},
    )
