// Fallback copy so the UI renders before the API responds, and if it is down.
export const FALLBACK_UI = {
  en: {
    tagline: 'Krish (farming) + Nova (new) = New Farming',
    intro: 'Upload a photo of a single leaf.',
    analyze: 'Analyze Leaf',
    analyzing: 'Analyzing the leaf, please wait...',
    results: 'Results',
    confidence: 'Confidence',
    language: 'Language',
    voice: 'Voice output',
    voice_on: 'On',
    voice_off: 'Off',
    voice_choice: 'Voice',
    voice_auto: 'Automatic (best available)',
    no_local_voice: 'No voice on this device for this language, so audio comes from the server. This needs an internet connection.',
    rank: 'Rank',
    disease: 'Predicted disease',
    remedy_for: 'Remedy for',
    replay: 'Speak again',
    new_scan: 'Diagnose another leaf',
    generating_voice: 'Generating audio...',
    low_confidence: 'Confidence is low. Try a clearer photo.',
    voice_failed: 'Could not generate audio. Check the backend and internet.',
    server_voice_note:
      'Your browser has no voice for this language, so audio is generated by the server. This needs an internet connection.',
    no_voice_and_no_server:
      'Your browser has no voice for this language and the server is unreachable, so audio cannot play.',
    api_down: 'Krishva cannot reach its server.',
    api_down_local: 'Start it with: uvicorn main:app --port 8000',
    api_down_hosted: 'A public backend URL must be set in src/lib/api.js',
    footer: 'Krishva - New Farming. Built for Indian farmers.',
  },
  hi: {
    tagline: 'कृषि (खेती) + नव (नया) = नई खेती',
    intro: 'एक पत्ती की फोटो अपलोड करें।',
    analyze: 'विश्लेषण करें',
    analyzing: 'पत्ती का विश्लेषण हो रहा है, कृपया प्रतीक्षा करें...',
    results: 'परिणाम',
    confidence: 'विश्वास स्तर',
    language: 'भाषा',
    voice: 'आवाज़',
    voice_on: 'चालू',
    voice_off: 'बंद',
    voice_choice: 'आवाज़',
    voice_auto: 'स्वतः (उपलब्ध सर्वश्रेष्ठ)',
    no_local_voice: 'इस डिवाइस पर इस भाषा की कोई आवाज़ नहीं है, इसलिए आवाज़ सर्वर से आएगी। इसके लिए इंटरनेट चाहिए।',
    rank: 'स्थान',
    disease: 'पहचानी गई बीमारी',
    remedy_for: 'इसका उपाय',
    replay: 'फिर से सुनाएं',
    new_scan: 'एक और पत्ती की जाँच करें',
    generating_voice: 'आवाज़ बन रही है...',
    low_confidence: 'विश्वास स्तर कम है। साफ़ फोटो के साथ फिर कोशिश करें।',
    voice_failed: 'आवाज़ नहीं बन सकी। बैकएंड और इंटरनेट जाँचें।',
    server_voice_note:
      'आपके ब्राउज़र में इस भाषा की आवाज़ नहीं है, इसलिए आवाज़ सर्वर बनाएगा। इसके लिए इंटरनेट चाहिए।',
    no_voice_and_no_server:
      'इस भाषा के लिए ब्राउज़र में आवाज़ नहीं है और सर्वर भी उपलब्ध नहीं है।',
    api_down: 'कृष्वा अपने सर्वर तक नहीं पहुँच पाया।',
    api_down_local: 'इसे चलाएं: uvicorn main:app --port 8000',
    api_down_hosted: 'सार्वजनिक बैकएंड URL src/lib/api.js में सेट करना होगा',
    footer: 'कृष्वा - नई खेती। भारतीय किसानों के लिए।',
  },
};

// API copy wins when present so the backend stays the source of truth.
export function translator(apiUi, lang) {
  const fromApi = apiUi && apiUi[lang];
  const base = FALLBACK_UI[lang];
  return (key) => (fromApi && fromApi[key] !== undefined ? fromApi[key] : base[key] || '');
}
